CREATE TABLE SCP_CLIENTES(
CLI_CODIGO INT AUTO_INCREMENT,
	CLI_CID _CODIGO INT,
CLI_NOME  VARCHAR(45) NOT NULL,
CLI_TIPO VARCHAR(10) NOT NULL,
CLI_CONTATO VARCHAR(45),
CLI_CARGO VARCHAR(45),
CLI_ENDERECO VARCHAR(45),

PRIMARY KEY (CLI_CODIGO),
CONSTRAINT CLI_FK_CODIGO FOREIGN KEY (CLI_CID_CODIGO) REFERENCES SCP_CIDADES(CID_CODIGO)
);

CREATE TABLE SCP_PEDIDOS(
PED_CODIGO INT AUTO_INCREMENT,
PED_DATA  DATETIME NOT NULL,
	PED_FUN_CODIGO INT,
	PED_CLI_CODIGO INT,
PED_FRETE FLOAT,
PED_TIPO_ENVIO VARCHAR(20),

PRIMARY KEY (PED_CODIGO),
CONSTRAINT PED_FUN_FK_CODIGO FOREIGN KEY (PED_FUN_CODIGO) REFERENCES SCP_FUNCIONARIOS(FUN_CODIGO),
CONSTRAINT PED_CLI_FK_CODIGO FOREIGN KEY (PED_CLI_CODIGO) REFERENCES SCP_CLIENTES(CLI_CODIGO)
);

CREATE TABLE SCP_FUNCIONARIOS(
FUN_CODIGO INT AUTO_INCREMENT,
FUN_NOME  VARCHAR(45) NOT NULL,
FUN_SEXO VARCHAR(1) NOT NULL,
FUN_ESTADO_CIVIL VARCHAR(10),
FUN_RG VARCHAR(8),
FUN_CPF VARCHAR(11),
FUN_DATA_NASC DATETIME,
	FUN_CID_CODIGO INT,
	FUN_SET_SIGLA VARCHAR(10),
	FUN_FNC_CODIGO INT,
FUN_SALARIO FLOAT,
FUN_TELEFONE VARCHAR(15),
FUN_EMAIL VARCHAR(30),

PRIMARY KEY (CLI_CODIGO),
CONSTRAINT FUN_CID_FK_CODIGO FOREIGN KEY (FUN_CID_CODIGO) REFERENCES SCP_CIDADES(CID_CODIGO),
CONSTRAINT FUN_SET_FK_SIGLA FOREIGN KEY (FUN_SET_SIGLA) REFERENCES SCP_SETORES(SET_SIGLA),
CONSTRAINT FUN_FNC_FK_CODIGO FOREIGN KEY (FUN_FNC_CODIGO) REFERENCES SCP_FUNCOES(FNC_CODIGO)
);

CREATE TABLE SCP_CIDADES(
CID_CODIGO INT AUTO_INCREMENT,
	CID_PAI_SIGLA INT,
CID_NOME  VARCHAR(45) NOT NULL, 

PRIMARY KEY (CID_CODIGO),
CONSTRAINT CID_FK_PAI FOREIGN KEY (CID_PAI_SIGLA) REFERENCES SCP_PAISES(PAI_SIGLA)
);

CREATE TABLE SCP_PAISES(
PAI_SIGLA INT  AUTO_INCREMENT,
PAI_NOME  VARCHAR(45) NOT NULL
);

CREATE TABLE SCP_SETORES(
SET_SIGLA INT  AUTO_INCREMENT,
SET_NOME  VARCHAR(45) NOT NULL
SET_RAMAL  VARCHAR(4) NOT NULL
SET_FUN_CODIGO  INT

PRIMARY KEY (SET_SIGLA),
CONSTRAINT SET_FK_SIGLA FOREIGN KEY (SET_FUN_CODIGO) REFERENCES SCP_FUNCIONARIOS(FUN_CODIGO)

);

CREATE TABLE SCP_FUNCOES(
PAI_SIGLA INT  AUTO_INCREMENT,
PAI_NOME  VARCHAR(45) NOT NULL
);

DROP TABLE SCP_CLIENTES;
DROP TABLE SCP_CIDADES;